# Generated by Django 4.1.5 on 2023-02-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='age_end',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='animation',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Validated', models.BooleanField(default=False)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.animation')),
                ('mediatheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.mediatheque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
