# Generated by Django 4.1.5 on 2023-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_alter_animation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='age_end',
            field=models.PositiveIntegerField(),
        ),
    ]
